### ISSUE TITLE
Seems to need adjustments to work with Rails 5

### ISSUE THREAD

**Issue by MayamaTakeshi** [anteo/render-parent#1]
Hello, following your nice explanation regarding extending Redmine views (http://www.redmine.org/boards/3/topics/33949)
I tried to use render_parent with Redmine head that uses Rails 5.1.2.
But it failed with this:

/var/lib/gems/2.4.0/gems/render_parent-0.0.8/lib/render_parent/rails3/on_load_action_view.rb:25:in `block in <top (required)>': undefined method `alias_method_chain' for ActionView::Base:Class (NoMethodError)

I don't have much experience with rails actually (I am learning it by trying to write a plugin for redmine) but by doing some search i understand alias_method_chain was deprecated and it seems it must be replaced with Module#prepend.

**Comment by goutnet** [comment]
this gem is used by several redmine plugins... which makes them all incompatible with latest Redmine version (based on rails 5.1).

it would be nice if you had some time to fix this?

**Comment by MayamaTakeshi** [comment]
Closing as it was solved by this PR merge:
  https://github.com/anteo/render-parent/pull/2
